services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Automatically runs the data generation pipeline
    command: python train.py
    tty: true
    stdin_open: true
