import numpy as np
from pyscf.lib.parameters import BOHR
import torch

def write_cube_file(filepath, z, pos, min_coords, max_coords, grid_res, density_grid):
    """
    filepath: path to save the .cube file
    z: atomic numbers (N,)
    pos: atomic coordinates in Angstroms (N, 3)
    min_coords: (3,) minimum coordinates of the grid in Angstroms
    max_coords: (3,) maximum coordinates of the grid in Angstroms
    grid_res: integer, number of points along each dimension
    density_grid: (grid_res, grid_res, grid_res) tensor/array of scalar density values
    """
    if isinstance(z, torch.Tensor): z = z.numpy()
    if isinstance(pos, torch.Tensor): pos = pos.numpy()
    if isinstance(min_coords, torch.Tensor): min_coords = min_coords.numpy()
    if isinstance(max_coords, torch.Tensor): max_coords = max_coords.numpy()
    if isinstance(density_grid, torch.Tensor): density_grid = density_grid.numpy()

    num_atoms = len(z)
    
    # Convert Angstroms to Bohr
    min_bohr = min_coords / BOHR
    max_bohr = max_coords / BOHR
    pos_bohr = pos / BOHR
    
    # Compute voxel steps
    step = (max_bohr - min_bohr) / (grid_res - 1)
    
    with open(filepath, 'w') as f:
        # Header
        f.write("PI-NDF High Resolution Density Export\n")
        f.write("Generated by Neural Density Field\n")
        
        # Num atoms and origin
        f.write(f"{num_atoms:5d} {min_bohr[0]:12.6f} {min_bohr[1]:12.6f} {min_bohr[2]:12.6f}\n")
        
        # Grid vectors
        f.write(f"{grid_res:5d} {step[0]:12.6f} {0.0:12.6f} {0.0:12.6f}\n")
        f.write(f"{grid_res:5d} {0.0:12.6f} {step[1]:12.6f} {0.0:12.6f}\n")
        f.write(f"{grid_res:5d} {0.0:12.6f} {0.0:12.6f} {step[2]:12.6f}\n")
        
        # Atoms
        for i in range(num_atoms):
            atomic_num = int(z[i])
            # Charge is typically the same as atomic number for neutral atoms in this context
            charge = float(atomic_num)
            f.write(f"{atomic_num:5d} {charge:12.6f} {pos_bohr[i,0]:12.6f} {pos_bohr[i,1]:12.6f} {pos_bohr[i,2]:12.6f}\n")
            
        # Volumetric data
        # Cube format expects Z to vary fastest, then Y, then X
        # For our 3D tensor of shape (Nx, Ny, Nz), iterating as flattened in C-order naturally does this.
        density_flat = density_grid.flatten()
        
        # Write 6 values per line
        for i in range(0, len(density_flat), 6):
            chunk = density_flat[i:i+6]
            line = "".join([f"{val:13.5E}" for val in chunk])
            f.write(line + "\n")
